In [27]:
import sys
sys.path.append("../")
import tensorflow as tf
assert tf.__version__.startswith('2.'), 'This tutorial assumes Tensorflow 2.0+'
import voxelmorph.tf as vxm



In [3]:
filter = vxm.losses.MIND().get_filter(3)
filter

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.10650697, 0.786986  , 0.10650697], dtype=float32)>

In [4]:
filter = tf.constant(
    [
        [[0,0,0], [0,0.10650697, 0], [0,0,0]],
        [[0, 0.10650697,0],[0.10650697, 0.786986  , 0.10650697], [0,0.10650697,0]],
        [[0,0,0], [0,0.10650697, 0], [0,0,0]]
    ]
)

In [5]:
tensor = tf.constant(
    [
        [[1,2,3],[2,3,3], [2,3,3]],
        [[3,4,3],[5,6,3], [2,3,3]],
        [[7,8,3],[9,0,3], [2,3,3]]
    ],  dtype=tf.float32
)

In [6]:
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [2., 3., 3.],
        [2., 3., 3.]],

       [[3., 4., 3.],
        [5., 6., 3.],
        [2., 3., 3.]],

       [[7., 8., 3.],
        [9., 0., 3.],
        [2., 3., 3.]]], dtype=float32)>

In [7]:
vxm.losses.MIND().shift(tensor, 1, 0, 0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[7., 8., 3.],
        [9., 0., 3.],
        [2., 3., 3.]],

       [[1., 2., 3.],
        [2., 3., 3.],
        [2., 3., 3.]],

       [[3., 4., 3.],
        [5., 6., 3.],
        [2., 3., 3.]]], dtype=float32)>

In [8]:
tf.nn.convolution(tensor, filter )

<tf.Tensor: shape=(3, 1, 3), dtype=float32, numpy=
array([[[0.31952092, 3.4260278 , 0.31952092]],

       [[0.63904184, 6.3195205 , 0.63904184]],

       [[0.        , 2.4496603 , 0.        ]]], dtype=float32)>

In [9]:
tensor.shape

TensorShape([3, 3, 3])

In [10]:
filter = vxm.losses.MIND().get_filter(3)
filter
filter.shape

TensorShape([3])

In [11]:
f1 = tf.reshape(filter,[1,1,3])
f1

<tf.Tensor: shape=(1, 1, 3), dtype=float32, numpy=array([[[0.10650697, 0.786986  , 0.10650697]]], dtype=float32)>

In [12]:
f2 = tf.reshape(filter,[1,3,1])
f2

<tf.Tensor: shape=(1, 3, 1), dtype=float32, numpy=
array([[[0.10650697],
        [0.786986  ],
        [0.10650697]]], dtype=float32)>

In [13]:
f3 = tf.reshape(filter,[3,1,1])
f3

<tf.Tensor: shape=(3, 1, 1), dtype=float32, numpy=
array([[[0.10650697]],

       [[0.786986  ]],

       [[0.10650697]]], dtype=float32)>

In [14]:
result = tf.nn.convolution(tensor, f1)
# result = tf.nn.convolution(result, f2)
# result = tf.nn.convolution(result, f3)
result

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.10650697, 1.573972  , 0.31952092],
        [0.21301395, 2.360958  , 0.31952092],
        [0.21301395, 2.360958  , 0.31952092]],

       [[0.31952092, 3.147944  , 0.31952092],
        [0.53253484, 4.721916  , 0.31952092],
        [0.21301395, 2.360958  , 0.31952092]],

       [[0.74554884, 6.295888  , 0.31952092],
        [0.95856273, 0.        , 0.31952092],
        [0.21301395, 2.360958  , 0.31952092]]], dtype=float32)>

In [15]:
f1 = tf.reshape(filter,[1,1,3,1,1])
f2 = tf.reshape(filter,[1,3,1,1,1])
f3 = tf.reshape(filter,[3,1,1,1,1])
tensor = tf.constant(
    [
        [[1,1,1],[1,1,1], [1,1,1]],
        [[1,1,1],[1,1,1], [1,1,1]],
        [[1,1,1],[1,1,1], [1,1,1]]
    ],  dtype=tf.float32
)
tensor = tf.reshape(tensor, [1,3,3,3,1])

In [16]:
result = tf.nn.convolution(tensor, f1, padding="SAME")
result = tf.nn.convolution(result, f2, padding="SAME")
result = tf.nn.convolution(result, f3, padding="SAME")
tf.squeeze(result)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.71330196, 0.79832953, 0.71330196],
        [0.7983296 , 0.8934928 , 0.7983296 ],
        [0.71330196, 0.7983296 , 0.71330196]],

       [[0.7983296 , 0.89349276, 0.7983296 ],
        [0.8934928 , 0.99999976, 0.8934928 ],
        [0.7983296 , 0.8934928 , 0.7983296 ]],

       [[0.7133019 , 0.79832953, 0.7133019 ],
        [0.7983296 , 0.8934928 , 0.7983296 ],
        [0.7133019 , 0.7983296 , 0.7133019 ]]], dtype=float32)>

In [17]:
f1

<tf.Tensor: shape=(1, 1, 3, 1, 1), dtype=float32, numpy=
array([[[[[0.10650697]],

         [[0.786986  ]],

         [[0.10650697]]]]], dtype=float32)>

In [18]:
f2

<tf.Tensor: shape=(1, 3, 1, 1, 1), dtype=float32, numpy=
array([[[[[0.10650697]]],


        [[[0.786986  ]]],


        [[[0.10650697]]]]], dtype=float32)>

In [19]:
tensor = tf.constant(
    [
        [[1,1,1],[1,1,1], [1,1,1]],
        [[1,1,1],[1,1,1], [1,1,1]],
        [[1,1,1],[1,1,1], [1,1,1]]
    ],  dtype=tf.float32
)

filter = vxm.losses.MIND().get_filter(3)
[xs,ys,zs] = vxm.losses.MIND().search_region()
Dp = tf.Variable(tf.zeros(tensor.shape + len(xs)))

In [20]:
tensor.shape

TensorShape([3, 3, 3])

In [21]:
output_list = []
for i in range(len(xs)):
    result = tf.math.square(tf.math.subtract(tensor, vxm.losses.MIND().shift(tensor, xs[i], ys[i], zs[i])))
    output_list.append(result)
    # if i == 6:
    #     break
Dp = tf.stack(output_list, axis=3)
Dp

<tf.Tensor: shape=(3, 3, 3, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0.

In [22]:
V = (tf.math.reduce_mean(Dp, axis=3))

In [23]:
tf.test.is_gpu_available()



Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [24]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]